### ISSUE TITLE
Homomorphic encryption - Package & publicize as a community package

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/proj-management#36]
- [x] Meet code standards
- [x] Add README with documentation
- [x] Write blog post for O(1) Labs blog about it--benefits and use cases
- [x] Twitter threads on benefits and use cases, and link to the Github repo

**Comment by nicc** [comment]
Context buddy: @jasongitmail / @barriebyron

**Comment by barriebyron** [comment]
@Trivo25 this package work is our first real-world test of the [Contributing guidelines](https://github.com/o1-labs/snarkyjs/blob/main/CONTRIBUTING.md) guidance and workflow for creating high-quality community packages 

I am looking at your [Twitter thread](https://docs.google.com/document/d/1-_BgPk3KfbVryxOCkqMyjd6HUS4aPwRl5Rcbl0Ffauo/edit) now

We can also use a Google doc for the blog post review cycle.

**Comment by mitschabaude** [comment]
I looked at the [snarkyjs-elgamal](https://github.com/Trivo25/snarkyjs-elgamal) repo and I think it's good to add as a community package!

**Comment by barriebyron** [comment]
@Trivo25 we can use https://github.com/o1-labs/snarkyjs/pull/857 for adding the package to the official list!

**Comment by barriebyron** [comment]
@Trivo25 blog post draft in Google doc [Unlocking the Power of Privacy: How Developers Can Leverage Homomorphic Encryption and Zero-Knowledge Proofs](https://docs.google.com/document/d/17VoKiU_BPyDic01kL_sk95Zy0m2w1WUZijAsaxCTT14/edit#heading=h.bvzlorpuevns)

**Comment by Trivo25** [comment]
https://twitter.com/zktrivo/status/1651677106592444417
